dist: trusty
sudo: required
language: bash

before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh | bash
notifications:
  slack:
    rooms:
      secure: 19Ei74lxnevBV2rE05Qrebz1+h3cqd2T1gxE6wDZhf49/DVA1DoHaeB6LXOt+DrOZonVXm7OkdKiFu95NWkjdlkYdtMB+zo9vKh7PPrG9HvIOUClb0mcm97RiIX+e54OBaoRPiuMQHqhkQ+cBsqcfN4sTXAy8LXynyLYl0Ht3yw2riq+dXymA6/qEK+36GCYc1D3tex7NlKiVJRTZe4KwbxXdOaKHfwt1y8IUrQUL+95B/+h0lb6NbG/eiFkJWT4I/728h3ZYNBA52PCw/T21akGJx4zBEnjp4mfyLbWhmakB+bTNtpTkThX5WCEulGHGTiIzjM7zQMtULcw0sdaOSOLuhxgj7/nPDkx33AxVw7G8NOOqD5qd3K3ltkgv+66oDYm4WdUH4xTULO1w4qffTfilS5AovgfMZq3tvFrjCqoWUZv9UTOi659sV8M5G7baeXBnAAeWZ7HgUkkWCbOzwMFeKV/27elT0G8SX/3xk+USwZIWo7Kvdxx2atk6jtKXPdJ/VY/kbkbFpQmozxgrHN/9CQ2AC/mngL/qDGVys0qnEQqT9jRrlgzF+gKHjkvW4wO/lQS2HF5z0VDDhzDIZq7EtexZCzEk7V+FERrCog2EkuY8h9ot49wRsZoFGcE9znIg5khKxyT7i9xUSVFXpHtaafvJHthAyIItbW5pEE=
