global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#stanislav_podporin'
