version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    networks:
      - back_net
      - front_net
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
    networks:
      - back_net
      - front_net
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.4.0
    networks:
      - back_net
      - front_net
    ports:
      - "5601:5601"

  zipkin:
    image: openzipkin/zipkin:2.21.0
    networks:
      - back_net
      - front_net
    ports:
      - "9411:9411"

networks:
  #  reddit:
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
