version: '3.4'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - ${VOLUME_DB_NAME}:${PATH_TO_VOLUME_DB}
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
#    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${HOST_PORT}:${UI_PORT}
    networks:
      - front_net
#      - reddit
  post:
#    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
#      - reddit
      - front_net
      - back_net
  comment:
#    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
#      - reddit

#  prometheus:
#    image: ${USERNAME}/prometheus
#    ports:
#      - '9090:9090'
#    volumes:
#      - prometheus_data:/prometheus
#    networks:
#      - front_net
#      - back_net
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день

#  node-exporter:
#    image: prom/node-exporter:v0.15.2
#    user: root
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /:/rootfs:ro
#    networks:
#      - front_net
#      - back_net
#    command:
#      - '--path.procfs=/host/proc'
#      - '--path.sysfs=/host/sys'
#      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

#  mongodb-exporter:
#    image: ${USERNAME}/mongodb_exporter:1.0
#    networks:
#      - back_net
#    command:
#      - '--mongodb.uri=mongodb://post_db:27017'

#  blackbox-exporter:
#    image: zlayasova/blackbox-exporter:v0.18.0
#    networks:
#      - back_net
#      - front_net
#    command:
#      - '--config.file=/etc/blackbox/config.yml'

volumes:
  post_db:
#  prometheus_data:

networks:
#  reddit:
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
