version: '3.4'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - ${VOLUME_DB_NAME}:${PATH_TO_VOLUME_DB}
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${HOST_PORT}:${UI_PORT}
    networks:
      - front_net
#      - reddit
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
#      - reddit
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
#      - reddit

volumes:
  post_db:

networks:
#  reddit:
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
          gateway: 10.0.2.1
